### ISSUE TITLE
No connection 999.0;0.0;0.0

### ISSUE THREAD

**Issue by lucamancusodev** [Wlanfr3ak/auto-speedtest#5]
Hello,

Thank you for sharing your project, after I installed all the necessary things if I run the script without crontab I get normal value in the csv, but when I run it on crontab the script writes into csv only 999 ping values like if there is not connection.

Tried also with root user.

**Comment by Wlanfr3ak** [comment]
So far I have not heard of such a mistake. I would guess that it has something to do with the user rights. Does the crontab user possibly have no permission for the network connection?

**Comment by lucamancusodev** [comment]
I don't think that is a user problem, also tried with root crontab with the same result.
How do you check if there is not connection?

**Comment by Wlanfr3ak** [comment]
There is no test for this in the software. This must then be done by the module "speedtest-cli" -> [https://github.com/sivel/speedtest-cli/](url)

**Comment by lucamancusodev** [comment]
I tried to delete the "if" part at the end leaving only the echo but now i got only date e time in the csv.
Maybe the crontab do not have the PATH for launch "speedtest-cli" or "speedtest"?

**Comment by lucamancusodev** [comment]
**Found**: need to add in the script the path of speedtest.
from vf=$(speedtest --simple) 
to 
vf=$(/usr/local/bin/speedtest --simple)

**Comment by Wlanfr3ak** [comment]
I added the solution in the master branch, thank you for sharing your solution!
