### ISSUE TITLE
/usr/local/bin/speedtest : No such file or directory

### ISSUE THREAD

**Issue by MildlyInterested** [Wlanfr3ak/auto-speedtest#6]
Throwing this error using the most up to date version of speedtest-cli installed via apt-get.
Uncommenting line 14 in speedtest.sh and removing "--server 4617" (server can't be reached so I just leave it up to ookla to pick the right one) fixes it.
Obviously comment out lilne 16.

I would create a pull request but will have to read up on how to do so. 

Issue happened on latest install of Ubuntu 20.04.1 LTS.

**Comment by Wlanfr3ak** [comment]
Yes the ID is outdated :-( I fix this directly and Thank You for the Feedback!
